---
- name: Test ping host all
  hosts: docker
  #become: yes
  gather_facts: yes
  tasks:
  - name: Git checkout
    ping:

  - name: Install the version '1.18.0' of package "nginx" and allow potential downgrades
    ansible.builtin.apt:
      name: nginx
      state: present
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: nginx
      enabled: yes

  - name: Just force systemd to reread configs (2.4 and above)
    ansible.builtin.systemd:
      daemon_reload: yes



  - name: Delete
    file:
      path:  /var/www/html
      state: absent


  - name: Create
    file:
      path:  /var/www/html
      state: directory



  - name: Unarchive a file with extra options
    unarchive:
      src: app.zip
      dest: /var/www/html
